version: 2

before:
  hooks:
    - go mod tidy
    - make sync-schemas

builds:
  - id: small
    main: ./cmd/small
    binary: small
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/justyn-clark/small-protocol/internal/version.Version={{.Version}}
      - -X github.com/justyn-clark/small-protocol/internal/version.Commit={{.Commit}}
      - -X github.com/justyn-clark/small-protocol/internal/version.Date={{.Date}}

archives:
  - id: small
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Version }}-dev+{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: justyn-clark
    name: small-protocol
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## SMALL Protocol {{ .Tag }}

    Install with:
    ```bash
    go install github.com/justyn-clark/small-protocol/cmd/small@{{ .Tag }}
    ```

    Or download pre-built binaries below.
