package commands

import "github.com/justyn-clark/small-protocol/internal/small"

var (
	intentTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "human"
intent: "Define project intent"
scope:
  include: []
  exclude: []
success_criteria: []
`

	constraintsTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "human"
constraints:
  - id: "no-secrets"
    rule: "No secrets in .small artifacts"
    severity: "error"
  - id: "no-prod-writes"
    rule: "No writes to production by default"
    severity: "error"
`

	planTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "agent"
tasks:
  - id: "task-1"
    title: "Initial task"
    steps: []
    acceptance: []
`

	progressTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "agent"
entries: []
`

	// SMALL harness block markers
	agentsBlockBegin = "<!-- BEGIN SMALL HARNESS v" + small.ProtocolVersion + " -->"
	agentsBlockEnd   = "<!-- END SMALL HARNESS v" + small.ProtocolVersion + " -->"

	// agentsBlockContent is the content inside the SMALL harness block (without markers)
	agentsBlockContent = `# SMALL Execution Harness

This section is generated by ` + "`small init`" + ` or ` + "`small agents apply`" + `.
Do not edit manually unless you know what you are doing.

## Required Commands

Before work:

1. Run ` + "`small status --json`" + `
2. Run ` + "`small check --strict`" + `

After any SMALL state change, run ` + "`small check --strict`" + ` again before ending the turn.
Use the installed ` + "`small`" + ` binary. Do not rely on ` + "`npx small`" + ` in offline or locked-down environments because it may try to fetch a package.

## Ownership Rules

Files in ` + "`.small/`" + ` have explicit ownership:

| File | Owner | Description |
|------|-------|-------------|
| intent.small.yml | human | Project intent and success criteria |
| constraints.small.yml | human | Hard constraints agents must follow |
| plan.small.yml | agent | Task breakdown and execution plan |
| progress.small.yml | agent | Append-only work log |
| handoff.small.yml | agent | Resume context for next agent |
| workspace.small.yml | agent | Workspace metadata |

**Human-owned files**: Agents MUST NOT modify without explicit human approval. If strict mode fails because of intent.small.yml or constraints.small.yml, stop and hand off instead of changing those files.
**Agent-owned files**: Agents may modify within protocol rules and should prefer SMALL CLI commands over manual edits.

## Artifact Rules

This generated block describes v1 files. If ` + "`.small/profile.json`" + ` declares
` + "`2.0.0`" + `, treat immutable sessions/events/receipts as authority, pass
` + "`--session`" + ` for parallel work, and use ` + "`small reconcile`" + ` rather than
editing records. v2 defaults to solo and collaboration requires an explicit
` + "`small mode set collaborative`" + ` transition.

- progress.small.yml is append-only
- plan.small.yml is replaceable through the CLI
- handoff.small.yml is the only resume entrypoint
- repository modifications should run through ` + "`small apply --task <task-id> --cmd \"...\"`" + ` when this repo requires apply-bounded writes
- progress timestamps must be generated by the tool, not by hand

## Progress Commands

Use CLI-owned progress commands:

- Start work: ` + "`small progress add --task <task-id> --status in_progress --evidence \"...\"`" + `
- Finish work: ` + "`small checkpoint --task <task-id> --status completed --evidence \"...\"`" + `
- Block work: ` + "`small checkpoint --task <task-id> --status blocked --evidence \"...\"`" + `
- Capture command output when needed: ` + "`small apply --task <task-id> --auto-progress --cmd \"...\"`" + `
- Use audit telemetry when needed: ` + "`SMALL_PROGRESS_MODE=audit small apply --task <task-id> --cmd \"...\"`" + `

Never hand-write timestamps in progress.small.yml.

## Canonical Examples

Valid plan.small.yml task shape:

~~~yaml
small_version: "1.0.0"
owner: "agent"
tasks:
  - id: "task-1"
    title: "Implement bounded change"
    status: "pending"
    steps:
      - "Run: small check --strict"
    acceptance:
      - "small check --strict passes"
~~~

Valid progress.small.yml entry shape:

~~~yaml
small_version: "1.0.0"
owner: "agent"
entries:
  - task_id: "task-1"
    status: "in_progress"
    timestamp: "2026-01-01T00:00:00.000000000Z"
    evidence: "Started via small progress add"
~~~

Valid handoff.small.yml shape:

~~~yaml
small_version: "1.0.0"
owner: "agent"
summary: "Run in progress. Next task: task-1."
resume:
  current_task_id: "task-1"
  next_steps:
    - "Continue with task-1"
links:
  - url: "https://example.com/context"
    description: "Context reference"
replayId:
  value: "0000000000000000000000000000000000000000000000000000000000000000"
  source: "manual"
~~~

## Field Gotchas

- Timestamps are RFC3339Nano UTC with fractional seconds and must be strictly increasing.
- links entries are objects with url and optional description, not strings.
- Quote YAML scalars that contain colon-space, such as "Run: small check --strict".
- progress.small.yml is append-only: add entries, never reorder or rewrite existing entries.

## Strict Mode Rules

` + "`small check --strict`" + ` enforces additional invariants:
- S1: Completed/blocked tasks must have progress entries with evidence
- S2: All progress task_ids must reference valid plan tasks or use the meta/ prefix
- S3: Handoff current_task_id must exist in plan
- S4: No unknown files or subdirectories under .small/

## Localhost HTTP Allowlist (Strict Mode)

Insecure http:// links are blocked EXCEPT in progress.small.yml where these are allowed:
- http://localhost
- http://127.0.0.1
- http://0.0.0.0
- http://[::1]

## Optional Stop Hook

For Claude-style agents, a Stop hook can enforce structural validation outside agent memory. Use this as a starting point and adapt paths per environment:

~~~json
{
  "hooks": {
    "Stop": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": "small check --strict"
          }
        ]
      }
    ]
  }
}
~~~

## Ralph Loop Behavior

When blocked or unable to proceed, agents MUST:

1. **Record in progress**: Add an entry explaining the blocker
2. **Update handoff**: Set resume.current_task_id and document the issue in next_steps
3. **Stop**: Do not attempt workarounds or unauthorized actions

This ensures human operators can review and unblock safely.
`
)

// GenerateAgentsBlock returns the full SMALL harness block with BEGIN/END markers.
func GenerateAgentsBlock() string {
	return agentsBlockBegin + "\n" + agentsBlockContent + agentsBlockEnd + "\n"
}
