package commands

import "github.com/justyn-clark/small-protocol/internal/small"

var (
	intentTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "human"
intent: "Define project intent"
scope:
  include: []
  exclude: []
success_criteria: []
`

	constraintsTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "human"
constraints:
  - id: "no-secrets"
    rule: "No secrets in .small artifacts"
    severity: "error"
  - id: "no-prod-writes"
    rule: "No writes to production by default"
    severity: "error"
`

	planTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "agent"
tasks:
  - id: "task-1"
    title: "Initial task"
    steps: []
    acceptance: []
`

	progressTemplate = `small_version: "` + small.ProtocolVersion + `"
owner: "agent"
entries: []
`

	// SMALL harness block markers
	agentsBlockBegin = "<!-- BEGIN SMALL HARNESS v" + small.ProtocolVersion + " -->"
	agentsBlockEnd   = "<!-- END SMALL HARNESS v" + small.ProtocolVersion + " -->"

	// agentsBlockContent is the content inside the SMALL harness block (without markers)
	agentsBlockContent = `# SMALL Execution Harness

This section is generated by ` + "`small init`" + ` or ` + "`small agents apply`" + `.
Do not edit manually unless you know what you are doing.

## Ownership Rules

Files in ` + "`.small/`" + ` have explicit ownership:

| File | Owner | Description |
|------|-------|-------------|
| intent.small.yml | human | Project intent and success criteria |
| constraints.small.yml | human | Hard constraints agents must follow |
| plan.small.yml | agent | Task breakdown and execution plan |
| progress.small.yml | agent | Append-only work log |
| handoff.small.yml | agent | Resume context for next agent |
| workspace.small.yml | agent | Workspace metadata |

**Human-owned files**: Agents MUST NOT modify without explicit human approval.
**Agent-owned files**: Agents may modify freely within protocol rules.

## Artifact Rules

- progress.small.yml is append-only
- plan.small.yml is replaceable
- handoff.small.yml is the only resume entrypoint

## Strict Mode Rules

` + "`small check --strict`" + ` enforces additional invariants:
- S1: Completed/blocked tasks must have progress entries with evidence
- S2: All progress task_ids must reference valid plan tasks (or use meta/ prefix)
- S3: Handoff current_task_id must exist in plan

## Localhost HTTP Allowlist (Strict Mode)

Insecure http:// links are blocked EXCEPT in progress.small.yml where these are allowed:
- http://localhost
- http://127.0.0.1
- http://0.0.0.0
- http://[::1]

## Ralph Loop Behavior

When blocked or unable to proceed, agents MUST:

1. **Record in progress**: Add an entry explaining the blocker
2. **Update handoff**: Set resume.current_task_id and document the issue in next_steps
3. **Stop**: Do not attempt workarounds or unauthorized actions

This ensures human operators can review and unblock safely.
`
)

// GenerateAgentsBlock returns the full SMALL harness block with BEGIN/END markers.
func GenerateAgentsBlock() string {
	return agentsBlockBegin + "\n" + agentsBlockContent + agentsBlockEnd + "\n"
}
