// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/spec": {
    params: {};
  };
  "/compliance": {
    params: {};
  };
  "/reference-workflow": {
    params: {};
  };
  "/blog/ai-needs-execution": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/docs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/protocol/small/v1": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/spec" | "/compliance" | "/reference-workflow" | "/blog/ai-needs-execution" | "/pricing" | "/contact" | "/docs" | "/docs/:slug" | "/protocol/small/v1" | "/*";
  };
  "./modules/shell/routes/marketing-layout.route.tsx": {
    id: "modules/shell/routes/marketing-layout.route";
    page: "/" | "/about" | "/spec" | "/compliance" | "/reference-workflow" | "/blog/ai-needs-execution" | "/pricing" | "/contact";
  };
  "./modules/marketing/routes/home.route.tsx": {
    id: "modules/marketing/routes/home.route";
    page: "/";
  };
  "./modules/marketing/routes/about.route.tsx": {
    id: "modules/marketing/routes/about.route";
    page: "/about";
  };
  "./modules/marketing/routes/spec.route.tsx": {
    id: "modules/marketing/routes/spec.route";
    page: "/spec";
  };
  "./modules/marketing/routes/compliance.route.tsx": {
    id: "modules/marketing/routes/compliance.route";
    page: "/compliance";
  };
  "./modules/workflow/routes/reference-workflow.route.tsx": {
    id: "modules/workflow/routes/reference-workflow.route";
    page: "/reference-workflow";
  };
  "./modules/marketing/routes/blog/ai-needs-execution.route.tsx": {
    id: "modules/marketing/routes/blog/ai-needs-execution.route";
    page: "/blog/ai-needs-execution";
  };
  "./modules/marketing/routes/pricing.route.tsx": {
    id: "modules/marketing/routes/pricing.route";
    page: "/pricing";
  };
  "./modules/marketing/routes/contact.route.tsx": {
    id: "modules/marketing/routes/contact.route";
    page: "/contact";
  };
  "./modules/shell/routes/docs-layout.route.tsx": {
    id: "modules/shell/routes/docs-layout.route";
    page: "/docs" | "/docs/:slug";
  };
  "./modules/docs/routes/docs-index.route.tsx": {
    id: "modules/docs/routes/docs-index.route";
    page: "/docs";
  };
  "./modules/docs/routes/doc.route.tsx": {
    id: "modules/docs/routes/doc.route";
    page: "/docs/:slug";
  };
  "./routes/protocol.small-v1.route.ts": {
    id: "routes/protocol.small-v1.route";
    page: "/protocol/small/v1";
  };
  "./routes/catch-all.route.tsx": {
    id: "routes/catch-all.route";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "modules/shell/routes/marketing-layout.route": typeof import("./app/./modules/shell/routes/marketing-layout.route.tsx");
  "modules/marketing/routes/home.route": typeof import("./app/./modules/marketing/routes/home.route.tsx");
  "modules/marketing/routes/about.route": typeof import("./app/./modules/marketing/routes/about.route.tsx");
  "modules/marketing/routes/spec.route": typeof import("./app/./modules/marketing/routes/spec.route.tsx");
  "modules/marketing/routes/compliance.route": typeof import("./app/./modules/marketing/routes/compliance.route.tsx");
  "modules/workflow/routes/reference-workflow.route": typeof import("./app/./modules/workflow/routes/reference-workflow.route.tsx");
  "modules/marketing/routes/blog/ai-needs-execution.route": typeof import("./app/./modules/marketing/routes/blog/ai-needs-execution.route.tsx");
  "modules/marketing/routes/pricing.route": typeof import("./app/./modules/marketing/routes/pricing.route.tsx");
  "modules/marketing/routes/contact.route": typeof import("./app/./modules/marketing/routes/contact.route.tsx");
  "modules/shell/routes/docs-layout.route": typeof import("./app/./modules/shell/routes/docs-layout.route.tsx");
  "modules/docs/routes/docs-index.route": typeof import("./app/./modules/docs/routes/docs-index.route.tsx");
  "modules/docs/routes/doc.route": typeof import("./app/./modules/docs/routes/doc.route.tsx");
  "routes/protocol.small-v1.route": typeof import("./app/./routes/protocol.small-v1.route.ts");
  "routes/catch-all.route": typeof import("./app/./routes/catch-all.route.tsx");
};